"""Add status to JobTarget

Revision ID: 1e8add6e9fc6
Revises: ed046679bc31
Create Date: 2026-06-25 21:52:56.876033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8add6e9fc6'
down_revision: Union[str, Sequence[str], None] = 'ed046679bc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_targets', sa.Column('status', sa.String(), server_default="Saved", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_targets', 'status')
    # ### end Alembic commands ###
