"""Add ATS score and strengths

Revision ID: 9a862c6bbb53
Revises: 61df7722f2ab
Create Date: 2026-06-25 19:24:26.711621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a862c6bbb53'
down_revision: Union[str, Sequence[str], None] = '61df7722f2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('weaknesses', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'weaknesses')
    op.drop_column('resumes', 'strengths')
    op.drop_column('resumes', 'ats_score')
    # ### end Alembic commands ###
