"""Add JobTracker columns

Revision ID: abb661062df8
Revises: b3d405cd7f66
Create Date: 2026-06-25 20:07:09.967962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb661062df8'
down_revision: Union[str, Sequence[str], None] = 'b3d405cd7f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_targets', sa.Column('company_url', sa.String(), nullable=True))
    op.add_column('job_targets', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('job_targets', sa.Column('fit_score', sa.Integer(), nullable=True))
    op.add_column('job_targets', sa.Column('aligned_skills', sa.Text(), nullable=True))
    op.add_column('job_targets', sa.Column('missing_skills', sa.Text(), nullable=True))
    op.add_column('job_targets', sa.Column('job_quality_summary', sa.Text(), nullable=True))
    op.add_column('job_targets', sa.Column('company_stability_summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'job_targets', 'resume_versions', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_targets', type_='foreignkey')
    op.drop_column('job_targets', 'company_stability_summary')
    op.drop_column('job_targets', 'job_quality_summary')
    op.drop_column('job_targets', 'missing_skills')
    op.drop_column('job_targets', 'aligned_skills')
    op.drop_column('job_targets', 'fit_score')
    op.drop_column('job_targets', 'company_name')
    op.drop_column('job_targets', 'company_url')
    # ### end Alembic commands ###
