"""B2C Pivot

Revision ID: b3d405cd7f66
Revises: 9a862c6bbb53
Create Date: 2026-06-25 19:45:40.731710

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3d405cd7f66"
down_revision: Union[str, Sequence[str], None] = "9a862c6bbb53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resume_id", sa.Integer(), nullable=True),
        sa.Column("job_description", sa.Text(), nullable=True),
        sa.Column("tailored_summary", sa.Text(), nullable=True),
        sa.Column("tailored_bullets", sa.Text(), nullable=True),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("interview_prep", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_targets_id"), "job_targets", ["id"], unique=False)
    op.create_index(
        op.f("ix_job_targets_resume_id"), "job_targets", ["resume_id"], unique=False
    )
    op.create_table(
        "resume_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("skills", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("education", sa.String(), nullable=True),
        sa.Column("past_titles", sa.Text(), nullable=True),
        sa.Column("ats_score", sa.Integer(), nullable=True),
        sa.Column("strengths", sa.Text(), nullable=True),
        sa.Column("weaknesses", sa.Text(), nullable=True),
        sa.Column("general_feedback", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resume_versions_email"), "resume_versions", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_resume_versions_filename"),
        "resume_versions",
        ["filename"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resume_versions_id"), "resume_versions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_resume_versions_phone"), "resume_versions", ["phone"], unique=False
    )
    op.drop_index(op.f("ix_resumes_email"), table_name="resumes")
    op.drop_index(op.f("ix_resumes_filename"), table_name="resumes")
    op.drop_index(op.f("ix_resumes_id"), table_name="resumes")
    op.drop_index(op.f("ix_resumes_phone"), table_name="resumes")
    op.drop_table("resumes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resumes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("extracted_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("skills", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("experience_years", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("education", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("past_titles", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ats_score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("strengths", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("weaknesses", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("resumes_pkey")),
    )
    op.create_index(op.f("ix_resumes_phone"), "resumes", ["phone"], unique=False)
    op.create_index(op.f("ix_resumes_id"), "resumes", ["id"], unique=False)
    op.create_index(op.f("ix_resumes_filename"), "resumes", ["filename"], unique=False)
    op.create_index(op.f("ix_resumes_email"), "resumes", ["email"], unique=False)
    op.drop_index(op.f("ix_resume_versions_phone"), table_name="resume_versions")
    op.drop_index(op.f("ix_resume_versions_id"), table_name="resume_versions")
    op.drop_index(op.f("ix_resume_versions_filename"), table_name="resume_versions")
    op.drop_index(op.f("ix_resume_versions_email"), table_name="resume_versions")
    op.drop_table("resume_versions")
    op.drop_index(op.f("ix_job_targets_resume_id"), table_name="job_targets")
    op.drop_index(op.f("ix_job_targets_id"), table_name="job_targets")
    op.drop_table("job_targets")
    # ### end Alembic commands ###
