"""Add jd positives and negatives

Revision ID: ed046679bc31
Revises: abb661062df8
Create Date: 2026-06-25 20:32:14.986748

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed046679bc31"
down_revision: Union[str, Sequence[str], None] = "abb661062df8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_targets", sa.Column("jd_positives", sa.Text(), nullable=True))
    op.add_column("job_targets", sa.Column("jd_negatives", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_targets", "jd_negatives")
    op.drop_column("job_targets", "jd_positives")
    # ### end Alembic commands ###
