"""drop deprecated job_quality_summary column

Revision ID: f97b428fc25b
Revises: 1e8add6e9fc6
Create Date: 2026-06-26 12:15:24.354563

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f97b428fc25b"
down_revision: Union[str, Sequence[str], None] = "1e8add6e9fc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_targets", "job_quality_summary")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_targets",
        sa.Column("job_quality_summary", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
